### ISSUE TITLE
Null pointer when streaming live data

### ISSUE THREAD

**Issue by katsully** [katsully/relevant-motion#1]
Stack Trace: 
```
wearnotch.notchdemo.tutorial E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wearnotch.notchdemo.tutorial, PID: 28700                     
    java.lang.NullPointerException: Attempt to invoke virtual method ‘java.io.File 
    com.wearnotch.service.network.impl.MeasurementImpl.getWorkoutFile()’ on a null object reference                                                                              
    at com.wearnotch.service.network.impl.operation.y.capture(SourceFile:550)
    at com.wearnotch.service.network.impl.android.c.capture(SourceFile:192)
    at com.wearnotch.notchdemo.MainFragment.capture(MainFragment.java:597)
    at com.wearnotch.notchdemo.MainFragment$24.onFinish(MainFragment.java:1132)
    at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7237)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
````

**Comment by katsully** [comment]
SOLVED: you must ensure the same number of notches being tracked match the same number of notches that are turned on. For example, when we were streaming 2 notches, we had 3 turned on and the third notch was triggering the error.

**Note: When you hit 'Configure Real Time' in the app, it should say 'Succeed' after a few seconds, if it's stuck on 'In Progress', that's another sign something is wrong.
